setwd("~/Desktop/thesis")
library(democracyData)
fh <- download_fh(verbose = FALSE)
library(countrycode)
fh$iso <- countrycode(fh$fh_country, "country.name", "iso3c", warn = TRUE)
write.csv(fh, "fh.csv")
polity <- download_polity_annual(verbose = FALSE)
write.csv(polity, "polity.csv")
citation(package = "democracyData")